# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-29 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20180429_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ID_number',
            field=models.CharField(default=1231, max_length=128, verbose_name='身份证号码'),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='a@qq.com', max_length=256, verbose_name='邮箱'),
        ),
    ]
