# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-29 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20180430_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='合同名称')),
                ('template', models.TextField()),
            ],
            options={
                'verbose_name_plural': '合同模板表',
            },
        ),
        migrations.AlterField(
            model_name='customer',
            name='ID_number',
            field=models.CharField(max_length=128, verbose_name='身份证号码'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=256, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='classlist',
            name='contract_templace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.ContractTemplate'),
        ),
    ]
