# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-04 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20180430_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='student_account',
            field=models.ForeignKey(blank=True, help_text='只有报名的客户，才可以关联学员账号。', null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Customer', verbose_name='学员'),
        ),
    ]
